// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/pixelpix-checkout/Current.tsx": () => import("../components/mockups/pixelpix-checkout/Current.tsx"),
  "./components/mockups/pixelpix-checkout/Guided.tsx": () => import("../components/mockups/pixelpix-checkout/Guided.tsx")
};
